# -*- coding: utf-8 -*-
"""main

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vQfZ7gfA0SpjJFxctWHtO-YC5BGVbLWB

# **Test Case**

**Before starting program, first import module cashier.py, then make a transaction id**
"""

import cashier as cs

#Create a transaction ID with function Transaction
transaction_1 = cs.Transaction()

"""**The customers will make an order by inputting the items purchased themself**"""

# Add items purchased
transaction_1.add_item()

"""**if there is a change of the item purchased, customer should update the item**"""

# Update item_name on order list
transaction_1.update_item()

# Update item_qty on order list
transaction_1.update_item_qty()

# Update item_price on order list
transaction_1.update_item_price()

"""**if the item is canceled to be purchased, customer can use function delete / reset item**"""

# Delete item on order list
transaction_1.delete_item()

# Reset transaction and delete all items on order list
transaction_1.reset_transaction()

"""**The customers make a new order by inputting the items purchased**"""

# Add new items purchased
transaction_1.add_item()

"""**Check order list, wheter it is appropriate or not**"""

# Check order list
transaction_1.check_transaction()

"""**The last, calculate the discount from total transaction, and total payment the customer have to pay**"""

# Calculate total_payment the customer have to pay
transaction_1.payment_transaction()